git:
  quiet: true
cache: yarn
language: node_js
node_js:
- '8'
- '10'
install:
- yarn
- yarn test
before_deploy:
  - yarn
  - yarn build
deploy:
  provider: npm
  email: czm.michael@gmail.com
  api_key:
    secure: p3VZMLuwiRn7ophlJ//zUT9Jk2X7959+UxFTdFUVd8LGHC/SSfkKN/fklsn6sZVf57OGtgSKmZExj8DwaG8C3hnZ3khrMSWIEJWDSd/VUh/iIMUkQFArsIvKhADyXg4ok+JrdfRkxsmhEuYw52HrTir/msEEUQAe0v6PCNxUl9TGDHrcIrzu5NcDOnJxW4+mE/QbmVyzOGepspBuKm7Ld2inRilTs7Wu3r1ZXgixbk0mcvR0z5bjUUE9OATjmwSsHREKq8R4eYIR/VljowjW1P1XJcSp6THJFOvQua14CczuxCwL4VRavnyFzR3Qh/iBppz9OpiuWDEKNpiCFy2Rwx5i8RcW4ZVVei/SRWyQv1gXAJiN4Pml4l28J9cSB/lkov+eGOPtN8/9wbroYrPkAZ/J74lcNnkWnwJcxkYgigC/6+E3SyicUA6ydfH7GB6flqh2dTiyNPshx3YxvT02We2grejs38EVg5fMuwuzPWpJXP1r+WLZAorpabXJZYc46AMgasy0GcR/QohWBBWqFoWrRew9lmKZ1sZMhFFFkU7Ft5/gdQ0VQ6CXubUzqDIeAWW8a6bSlR1RF/uqhs90AhFsgJBLCeBHWesRPRP5sTbcItBTUAm0BCJRK3IA1jOvNcP1PQMcWYvJXjwngOdiSp2nzApXag/D1ugwc78DphM=
  on:
    tags: true
    repo: michaelcai/hd-key
